version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local #Here we are using the already existing .env.local file
    # change from default postgres port to avoid overlap
    ports:
      - "5470:5432"

  db-test:
    image: postgres:latest
    env_file: ./.env.test.local
    ports:
      - 5471:5432

volumes:
  data:
